#!/bin/bash
. /root/.pulp/credentials

ENVIRO=$1
shift

DIR=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
export PATH=$DIR:$PATH

function updateall {
  repo=$1
  shift
  pulp-admin rpm repo update --repo-id=$repo $@
}

function login {
  pulp-admin login --username $PULP_USER \
                   --password $PULP_PASSWORD
}

function logout {
  pulp-admin logout
}

login

updateall centos-7-base-x86_64-$ENVIRO $@
updateall centos-7-updates-x86_64-$ENVIRO $@
updateall centos-6-base-x86_64-$ENVIRO $@
updateall centos-6-updates-x86_64-$ENVIRO $@
updateall centos-5-base-x86_64-$ENVIRO $@
updateall centos-5-updates-x86_64-$ENVIRO $@
updateall epel-5-x86_64-$ENVIRO $@
updateall epel-6-x86_64-$ENVIRO $@
updateall epel-7-x86_64-$ENVIRO $@

logout
